PLATFORM_REPORTS = {'pr', 'pr_p1'}

PLATFORM_REPORT_HEADER = {'report_name',
                          'report_id',
                          'release',
                          'institution_name',
                          'institution_id',
                          'metric_types',
                          'report_filters',
                          'report_attributes',
                          'exceptions',
                          'reporting_period',
                          'created',
                          'created_by'}

PLATFORM_REPORT_ELEMENTS = {'platform',
                            'data_type',
                            'access_method',
                            'metric_type',
                            'reporting_period_total',
                            'mmm-yyyy'}

PLATFORM_REPORT_METRICS = {'pr': {'searchers_platform',
                                  'total_item_investigations',
                                  'total_item_requests',
                                  'unique_item_investigations',
                                  'unique_item_requests',
                                  'unique_title_investigations',
                                  'unique_title_requests'},
                           'pr_p1': {'searchers_platform',
                                     'total_item_requests',
                                     'unique_item_requests',
                                     'unique_title_requests'}
                           }

TITLE_REPORTS = {'tr', 'tr_j1', 'tr_j2', 'tr_j3', 'tr_j4'}

TITLE_REPORT_HEADER = {'report_name',
                       'report_id',
                       'release',
                       'institution_name',
                       'institution_id',
                       'metric_types',
                       'report_filters',
                       'report_attributes',
                       'exceptions',
                       'reporting_period',
                       'created',
                       'created_by'}

TITLE_REPORT_ELEMENTS = {'title',
                         'publisher',
                         'publisher_id',
                         'platform',
                         'doi',
                         'proprietary_id',
                         'isbn',
                         'print_issn',
                         'online_issn',
                         'uri',
                         'data_type',
                         'section_type',
                         'yop',
                         'access_type',
                         'metric_type',
                         'reporting_period_total',
                         'mmm-yyyy'}

TITLE_REPORT_METRICS = {'tr': {'total_item_investigations',
                               'total_item_requests',
                               'unique_item_investigations',
                               'unique_item_requests'
                               'unique_title_investigations',
                               'unique_title_requests',
                               'limit_exceeded'
                               'no_licence'},
                        'tr_j1': {'total_item_requests',
                                  'unique_item_requests'},
                        'tr_j2': {'limit_exceeded',
                                  'no_licence'},
                        'tr_j3': {'total_item_investigations',
                                  'total_item_requests',
                                  'unique_item_investigations',
                                  'unique_item_requests'},
                        'tr_j4': {'total_item_requests',
                                  'unique_item_requests'}
                        }

ITEM_REPORTS = {'ir', 'ir_a1'}

ITEM_REPORT_HEADER = {'report_name',
                      'report_id',
                      'release',
                      'institution_name',
                      'institution_id',
                      'metric_types',
                      'report_filters',
                      'report_attributes',
                      'exceptions',
                      'reporting_period',
                      'created',
                      'created_by'}

ITEM_REPORT_METRICS = {'ir_a1': {'total_item_investigations',
                                 'total_item_requests',
                                 'unique_item_investigations',
                                 'unique_item_requests'}
                       }

ITEM_REPORT_ELEMENTS = {'item',
                        'publisher',
                        'publisher_id',
                        'platform',
                        'authors',
                        'publication_date',
                        'article_version',
                        'doi',
                        'proprietary_id',
                        'isbn',
                        'print_issn',
                        'online_issn',
                        'uri',
                        'parent_title',
                        'parent_authors',
                        'parent_publication_date',
                        'parent_article_version',
                        'parent_data_type',
                        'parent_doi',
                        'parent_proprietary_id',
                        'parent_isbn',
                        'parent_print_issn',
                        'parent_online_issn',
                        'parent_uri',
                        'component_title',
                        'component_authors',
                        'component_publication_date',
                        'component_data_type',
                        'component_doi',
                        'component_proprietary_id',
                        'component_isbn',
                        'component_print_issn',
                        'component_online_issn',
                        'component_uri',
                        'data_type',
                        'yop',
                        'access_type',
                        'access_method',
                        'metric_type',
                        'reporting_period_total',
                        'mmm-yyyy'}
