SCL_DOMAIN = '{0}'

# URLs passíveis de rastreamento
ACTION_SCLBR_ARTICLE_PLUS = SCL_DOMAIN + '/article_plus.php?'
ACTION_SCLBR_AVALIACAO = SCL_DOMAIN + '/avaliacao/'
ACTION_SCLBR_EQUIPE = SCL_DOMAIN + '/equipe'
ACTION_SCLBR_EQUIPE_EIP = SCL_DOMAIN + '/equipe_[e|i|p].htm'
ACTION_SCLBR_GOOGLE_METRICS_H5_M5 = SCL_DOMAIN + '/google_metrics/get_h5_m5.php?'
ACTION_SCLBR_IMG = SCL_DOMAIN + '/img'
ACTION_SCLBR_IMG_FBPE = ACTION_SCLBR_IMG + '/fbpe/'
ACTION_SCLBR_IMG_REVISTAS = ACTION_SCLBR_IMG + '/revistas/'
ACTION_SCLBR_PDF = SCL_DOMAIN + '/pdf/'
ACTION_SCLBR_READCUBE_EPDF = SCL_DOMAIN + '/readcube/epdf.php?'
ACTION_SCLBR_REVISTAS = SCL_DOMAIN + '/revistas'
ACTION_SCLBR_REVISTAS_ABOUT = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]aboutj.htm'
ACTION_SCLBR_REVISTAS_EDITORIAL_BOARD = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]edboard.htm'
ACTION_SCLBR_REVISTAS_INSTRUCTIONS = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]instruc.htm'
ACTION_SCLBR_REVISTAS_SUBSCRIPTION = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]subscrp.htm'
ACTION_SCLBR_RSS = SCL_DOMAIN + '/rss.php?'
ACTION_SCLBR_SCLORG_PHP = SCL_DOMAIN + '/scieloorg/php'
ACTION_SCLBR_SCLORG_PHP_ARTICLEXML = ACTION_SCLBR_SCLORG_PHP + '/articlexml.php?'
ACTION_SCLBR_SCLORG_PHP_CITEDSCIELO = ACTION_SCLBR_SCLORG_PHP + '/citedscielo.php?'
ACTION_SCLBR_SCLORG_PHP_DATASUS = ACTION_SCLBR_SCLORG_PHP + '/datasus.php?'
ACTION_SCLBR_SCLORG_PHP_REFERENCE = ACTION_SCLBR_SCLORG_PHP + '/reference.php?'
ACTION_SCLBR_SCLORG_PHP_REFLINKS = ACTION_SCLBR_SCLORG_PHP + '/reflinks.php?'
ACTION_SCLBR_SCLORG_PHP_RELATED = ACTION_SCLBR_SCLORG_PHP + '/related.php?'
ACTION_SCLBR_SCLORG_PHP_SIMILAR = ACTION_SCLBR_SCLORG_PHP + '/similar.php?'
ACTION_SCLBR_SCLORG_PHP_TRANSLATE = ACTION_SCLBR_SCLORG_PHP + '/translate.php?'
ACTION_SCLBR_SCLPHP = SCL_DOMAIN + '/scielo.php'
ACTION_SCLBR_SCLPHP_DOWNLOAD = ACTION_SCLBR_SCLPHP + '?download'
ACTION_SCLBR_SCLPHP_SCRIPT_SCI_ISSUES = ACTION_SCLBR_SCLPHP + '/script_sci_issues/pid_{}'
ACTION_SCLBR_SCLPHP_SCRIPT_SCI_SERIAL = ACTION_SCLBR_SCLPHP + '/script_sci_serial/pid_{}'
ACTION_SCLBR_STATJOURNAL = SCL_DOMAIN + '/statjournal.php?'
ACTION_SCLBR_WXIS = SCL_DOMAIN + '/cgi-bin/wxis.exe'

# URLs em formato novo passíveis de rastreamento
ACTION_NEW_SCLBR = 'new.scielo.br'
ACTION_NEW_SCLBR_EQUIPE = ACTION_NEW_SCLBR + '/about/equipe_scielo'
ACTION_NEW_SCLBR_PERIODICO = ACTION_NEW_SCLBR + '/j/{}'
ACTION_NEW_SCLBR_PERIODICO_ARTIGO = ACTION_NEW_SCLBR_PERIODICO + '/a/{}'
ACTION_NEW_SCLBR_PERIODICO_ARTIGO_RESUMO = ACTION_NEW_SCLBR_PERIODICO_ARTIGO + '/abstract/'
ACTION_NEW_SCLBR_PERIODICO_FASCICULOS = ACTION_NEW_SCLBR_PERIODICO + '/grid'
ACTION_NEW_SCLBR_PERIODICO_RSS = ACTION_NEW_SCLBR_PERIODICO + '/feed/'
ACTION_NEW_SCLBR_PERIODICO_TOC = ACTION_NEW_SCLBR_PERIODICO + '/i/{}/'
ACTION_NEW_SCLBR_PERIODICO_SOBRE = ACTION_NEW_SCLBR_PERIODICO + '/about/#about'
ACTION_NEW_SCLBR_PERIODICO_EDITORES = ACTION_NEW_SCLBR_PERIODICO + '/about/#editors'
ACTION_NEW_SCLBR_PERIODICO_INSTRUCOES = ACTION_NEW_SCLBR_PERIODICO + '/about/#instructions'
ACTION_NEW_SCLBR_PERIODICOS_ALFABETICO = ACTION_NEW_SCLBR + '/journals/alpha'
ACTION_NEW_SCLBR_PERIODICOS_TEMATICO = ACTION_NEW_SCLBR + '/journals/thematic'

# Tipos de Hit
HIT_TYPE_ARTICLE = 1
HIT_TYPE_ISSUE = 2
HIT_TYPE_JOURNAL = 3
HIT_TYPE_PLATFORM = 4
HIT_TYPE_OTHERS = -1

# Conteúdos relacionados a artigos
HIT_CONTENT_ARTICLE_FULL_TEXT = 1
HIT_CONTENT_ARTICLE_FULL_TEXT_PLUS = 2
HIT_CONTENT_ARTICLE_ARTICLE_XML = 3
HIT_CONTENT_ARTICLE_PDF = 4
HIT_CONTENT_ARTICLE_PLUS = 5
HIT_CONTENT_ARTICLE_ABSTRACT = 6
HIT_CONTENT_ARTICLE_ISOREF = 7
HIT_CONTENT_ARTICLE_PRESS_RELEASE = 8
HIT_CONTENT_ARTICLE_REQUEST_PDF = 9
HIT_CONTENT_ARTICLE_CITEDSCIELO = 10
HIT_CONTENT_ARTICLE_REFERENCE_LIST = 11
HIT_CONTENT_ARTICLE_RELATED = 12
HIT_CONTENT_ARTICLE_TRANSLATE = 13
HIT_CONTENT_ARTICLE_DOWNLOAD_CITATION = 14
HIT_CONTENT_ARTICLE_EXTERNAL_PDF = 15
# HIT_CONTENT_ARTICLE_NLINKS = 16 # PIDs são maiores que o permitido
# HIT_CONTENT_ARTICLE_DATASUS = 17 # PIDs possuem um formato diferente (começam com F)
# HIT_CONTENT_ARTICLE_REFLINKS = 18 # PIDs são maiores que o permitido e estão sob o parâmetro refpid

# Conteúdos relacionados a artigos no novo formato de URL
HIT_CONTENT_NEW_SCL_ARTICLE_HTML = 1001
HIT_CONTENT_NEW_SCL_ARTICLE_ABSTRACT = 1002
HIT_CONTENT_NEW_SCL_ARTICLE_XML = 1003
HIT_CONTENT_NEW_SCL_ARTICLE_PDF = 1004
HIT_CONTENT_NEW_SCL_ARTICLE_HOW_TO_CITE = 1007
HIT_CONTENT_NEW_SCL_ARTICLE_REQUEST_PDF = 1009
HIT_CONTENT_NEW_SCL_ARTICLE_TRANSLATE = 1013
HIT_CONTENT_NEW_SCL_ARTICLE_AUTHORS = 1019
HIT_CONTENT_NEW_SCL_ARTICLE_TABLES_AND_FIGURES = 1020

# Conteúdos relacionados a artigos preprint
HIT_CONTENT_TYPE_PREPRINT_ABSTRACT = 20001
HIT_CONTENT_TYPE_PREPRINT_PDF = 20002

# Conteúdos relacionados a fascículos
HIT_CONTENT_ISSUE_TOC = 51
HIT_CONTENT_ISSUE_RSS = 52

# Conteúdos relacionados a periódicos
HIT_CONTENT_JOURNAL_ISSUES = 101
HIT_CONTENT_JOURNAL_MAIN_PAGE = 102
HIT_CONTENT_JOURNAL_RSS = 103
HIT_CONTENT_JOURNAL_ABOUT = 104
HIT_CONTENT_JOURNAL_EDITORIAL = 105
HIT_CONTENT_JOURNAL_INSTRUCTIONS = 106
HIT_CONTENT_JOURNAL_SUBSCRIPTION = 107
HIT_CONTENT_JOURNAL_GOOGLE_METRICS = 108
HIT_CONTENT_JOURNAL_IMG_FBPE = 109
HIT_CONTENT_JOURNAL_IMG_REVISTAS = 110
HIT_CONTENT_JOURNAL_REVISTAS = 111
HIT_CONTENT_JOURNAL_SERIAL = 112
HIT_CONTENT_JOURNAL_STAT = 113

# Conteúdos relacionados a periódicos no novo formato de URL
HIT_CONTENT_NEW_SCL_JOURNAL_GRID = 10101
HIT_CONTENT_NEW_SCL_JOURNAL = 10102
HIT_CONTENT_NEW_SCL_JOURNAL_FEED = 10103
HIT_CONTENT_NEW_SCL_JOURNAL_TOC = 10114

# Conteúdos relacionados à plataforma
HIT_CONTENT_PLATFORM_LIST_JOURNALS_ALPHABETIC = 151
HIT_CONTENT_PLATFORM_HOME = 152
HIT_CONTENT_PLATFORM_LIST_JOURNALS_SUBJECT = 153
HIT_CONTENT_PLATFORM_EVALUATION = 154
HIT_CONTENT_PLATFORM_TEAM = 155
HIT_CONTENT_PLATFORM_MAIN_PAGE = 156
# HIT_CONTENT_PLATFORM_SEARCH = 157 # Interações internas da aplicação

# Conteúdos relacionados à plataforma no novo formato de URL
HIT_CONTENT_NEW_SCL_JOURNALS_ALPHABETIC = 10151
HIT_CONTENT_NEW_SCL_JOURNALS_THEMATIC = 10153
HIT_CONTENT_NEW_SCL_PLATFORM_TEAM = 10155

# Outros conteúdos
HIT_CONTENT_OTHERS = -1

# Conteúdos relacionados ao artigos do site Public Health
HIT_CONTENT_SSP_ARTICLE_HTML = 50001
HIT_CONTENT_SSP_ARTICLE_PDF = 50004

# Conteúdos relacionados a fascículos do site Public Health
HIT_CONTENT_SSP_ISSUE = 50051
HIT_CONTENT_SSP_ISSUE_RSS = 50052

# Conteúdos relacionados a periódicos do site Public Health
HIT_CONTENT_SSP_JOURNAL_ISSUES = 50101
HIT_CONTENT_SSP_JOURNAL_MAIN_PAGE = 50102
HIT_CONTENT_SSP_JOURNAL_RSS = 50103
HIT_CONTENT_SSP_JOURNAL_ABOUT = 50104

# Conteúdos relacionados ao site Public Health
HIT_CONTENT_SSP_PLATFORM_LIST_JOURNALS_ALPHABETIC = 50151
HIT_CONTENT_SSP_PLATFORM_HOME = 50152
HIT_CONTENT_SSP_PLATFORM_LIST_JOURNALS_THEMATIC = 50153
HIT_CONTENT_SSP_PLATFORM_ABOUT = 50158
