# URLs passíveis de rastreamento
ACTION_SCLBR = 'scielo.br'
ACTION_SCLBR_ARTICLE_PLUS = ACTION_SCLBR + '/article_plus.php?'
ACTION_SCLBR_AVALIACAO = ACTION_SCLBR + '/avaliacao/'
ACTION_SCLBR_EQUIPE = ACTION_SCLBR + '/equipe'
ACTION_SCLBR_EQUIPE_EIP = ACTION_SCLBR + '/equipe_[e|i|p].htm'
ACTION_SCLBR_GOOGLE_METRICS_H5_M5 = ACTION_SCLBR + '/google_metrics/get_h5_m5.php?'
ACTION_SCLBR_IMG = ACTION_SCLBR + '/img'
ACTION_SCLBR_IMG_FBPE = ACTION_SCLBR_IMG + '/fbpe/'
ACTION_SCLBR_IMG_REVISTAS = ACTION_SCLBR_IMG + '/revistas/'
ACTION_SCLBR_PDF = ACTION_SCLBR + '/pdf/'
ACTION_SCLBR_READCUBE_EPDF = ACTION_SCLBR + '/readcube/epdf.php?'
ACTION_SCLBR_REVISTAS = ACTION_SCLBR + '/revistas'
ACTION_SCLBR_REVISTAS_ABOUT = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]aboutj.htm'
ACTION_SCLBR_REVISTAS_EDITORIAL_BOARD = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]edboard.htm'
ACTION_SCLBR_REVISTAS_INSTRUCTIONS = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]instruc.htm'
ACTION_SCLBR_REVISTAS_SUBSCRIPTION = ACTION_SCLBR_REVISTAS + '/{}/[e|i|p]subscrp.htm'
ACTION_SCLBR_RSS = ACTION_SCLBR + '/rss.php?'
ACTION_SCLBR_SCLORG_PHP = ACTION_SCLBR + '/scieloorg/php'
ACTION_SCLBR_SCLORG_PHP_ARTICLEXML = ACTION_SCLBR_SCLORG_PHP + '/articlexml.php?'
ACTION_SCLBR_SCLORG_PHP_CITEDSCIELO = ACTION_SCLBR_SCLORG_PHP + '/citedscielo.php?'
ACTION_SCLBR_SCLORG_PHP_DATASUS = ACTION_SCLBR_SCLORG_PHP + '/datasus.php?'
ACTION_SCLBR_SCLORG_PHP_REFERENCE = ACTION_SCLBR_SCLORG_PHP + '/reference.php?'
ACTION_SCLBR_SCLORG_PHP_REFLINKS = ACTION_SCLBR_SCLORG_PHP + '/reflinks.php?'
ACTION_SCLBR_SCLORG_PHP_RELATED = ACTION_SCLBR_SCLORG_PHP + '/related.php?'
ACTION_SCLBR_SCLORG_PHP_SIMILAR = ACTION_SCLBR_SCLORG_PHP + '/similar.php?'
ACTION_SCLBR_SCLORG_PHP_TRANSLATE = ACTION_SCLBR_SCLORG_PHP + '/translate.php?'
ACTION_SCLBR_SCLPHP = ACTION_SCLBR + '/scielo.php'
ACTION_SCLBR_SCLPHP_DOWNLOAD = ACTION_SCLBR_SCLPHP + '?download'
ACTION_SCLBR_SCLPHP_SCRIPT_SCI_ISSUES = ACTION_SCLBR_SCLPHP + '/script_sci_issues/pid_{}'
ACTION_SCLBR_SCLPHP_SCRIPT_SCI_SERIAL = ACTION_SCLBR_SCLPHP + '/script_sci_serial/pid_{}'
ACTION_SCLBR_STATJOURNAL = ACTION_SCLBR + '/statjournal.php?'
ACTION_SCLBR_WXIS = ACTION_SCLBR + '/cgi-bin/wxis.exe'

# Tipos de Hit
HIT_TYPE_ARTICLE = 1
HIT_TYPE_ISSUE = 2
HIT_TYPE_JOURNAL = 3
HIT_TYPE_PLATFORM = 4
HIT_TYPE_OTHERS = -1

# Conteúdos relacionados a artigos
HIT_CONTENT_ARTICLE_FULL_TEXT = 1
HIT_CONTENT_ARTICLE_FULL_TEXT_PLUS = 2
HIT_CONTENT_ARTICLE_ARTICLE_XML = 3
HIT_CONTENT_ARTICLE_PDF = 4
HIT_CONTENT_ARTICLE_PLUS = 5
HIT_CONTENT_ARTICLE_ABSTRACT = 6
HIT_CONTENT_ARTICLE_ISOREF = 7
HIT_CONTENT_ARTICLE_PRESS_RELEASE = 8
HIT_CONTENT_ARTICLE_REQUEST_PDF = 9
HIT_CONTENT_ARTICLE_CITEDSCIELO = 10
HIT_CONTENT_ARTICLE_REFERENCE_LIST = 11
HIT_CONTENT_ARTICLE_RELATED = 12
HIT_CONTENT_ARTICLE_TRANSLATE = 13
HIT_CONTENT_ARTICLE_DOWNLOAD_CITATION = 14
HIT_CONTENT_ARTICLE_EXTERNAL_PDF = 15
# HIT_CONTENT_ARTICLE_NLINKS = 16 # PIDs são maiores que o permitido
# HIT_CONTENT_ARTICLE_DATASUS = 17 # PIDs possuem um formato diferente (começam com F)
# HIT_CONTENT_ARTICLE_REFLINKS = 18 # PIDs são maiores que o permitido e estão sob o parâmetro refpid

# Conteúdos relacionados a fascículos
HIT_CONTENT_ISSUE_TOC = 51
HIT_CONTENT_ISSUE_RSS = 52

# Conteúdos relacionados a periódicos
HIT_CONTENT_JOURNAL_ISSUES = 101
HIT_CONTENT_JOURNAL_MAIN_PAGE = 102
HIT_CONTENT_JOURNAL_RSS = 103
HIT_CONTENT_JOURNAL_ABOUT = 104
HIT_CONTENT_JOURNAL_EDITORIAL = 105
HIT_CONTENT_JOURNAL_INSTRUCTIONS = 106
HIT_CONTENT_JOURNAL_SUBSCRIPTION = 107
HIT_CONTENT_JOURNAL_GOOGLE_METRICS = 108
HIT_CONTENT_JOURNAL_IMG_FBPE = 109
HIT_CONTENT_JOURNAL_IMG_REVISTAS = 110
HIT_CONTENT_JOURNAL_REVISTAS = 111
HIT_CONTENT_JOURNAL_SERIAL = 112
HIT_CONTENT_JOURNAL_STAT = 113

# Conteúdos relacionados à plataforma
HIT_CONTENT_PLATFORM_LIST_JOURNALS_ALPHABETIC = 151
HIT_CONTENT_PLATFORM_HOME = 152
HIT_CONTENT_PLATFORM_LIST_JOURNALS_SUBJECT = 153
HIT_CONTENT_PLATFORM_EVALUATION = 154
HIT_CONTENT_PLATFORM_TEAM = 155
HIT_CONTENT_PLATFORM_MAIN_PAGE = 156
# HIT_CONTENT_PLATFORM_SEARCH = 157 # Interações internas da aplicação

# Outros conteúdos
HIT_CONTENT_OTHERS = -1
