COLLECTION_SCL = 'scl'
FORMAT_PDF = 'pdf'
FORMAT_HTML = 'html'
LANGUAGE_PT = 'pt'

# Coleção padrão
DEFAULT_COLLECTION = COLLECTION_SCL

# Formato padrão
DEFAULT_FORMAT = FORMAT_HTML

# Idioma padrão
DEFAULT_LANGUAGE = LANGUAGE_PT
