#!/bin/bash
MATOMO_DATABASE_USER=$1
MATOMO_DATABASE_PASS=$2
MATOMO_SITE_ID=$3
MATOMO_DATE_START=$4
MATOMO_DATE_END=$5
SCRIPT_PATH=$6

CURRENT_DATE=$MATOMO_DATE_START

while [ "$CURRENT_DATE" != "$MATOMO_DATE_END" ]; do
  NEXT_DATE=$(date -I -d "$CURRENT_DATE + 1 day")

  echo "Extracting pretable for site $MATOMO_SITE_ID and date [$CURRENT_DATE, $NEXT_DATE["
  sh "$SCRIPT_PATH" "$MATOMO_DATABASE_USER" "$MATOMO_DATABASE_PASS" "$MATOMO_SITE_ID" "$CURRENT_DATE" "$NEXT_DATE"
  
  CURRENT_DATE=$(date -I -d "$CURRENT_DATE + 1 day")
done
