DATE_STATUS_QUEUE = 0
DATE_STATUS_PARTIAL = 1
DATE_STATUS_LOADED = 2
DATE_STATUS_PRETABLE = 3
DATE_STATUS_COMPUTED = 4
DATE_STATUS_COMPLETED = 5
DATE_STATUS_EXTRACTING_PRETABLE = -3

AGGR_STATUS_QUEUE = 0
AGGR_STATUS_DONE = 1
